# Site settings
title: JianPing Site
email: lvjianping1987@gmail.com
description: "Focus on Data-Science & Finance."
baseurl: "/"
#url: ""
permalink: /:year/:title


# Social account
# twitter:  PeiwenLu
# weibo:    ID
github:   jianpingsky
# codepen:  P233
# dribbble: username


# Comment
# disqus_shortname:


# Google Analytics
google_analytics: UA-60830414-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
